// Romanian object government is authored per semantic tense family. Every
// verb family and every personal noun in the shipped catalog has an entry.
// The grammar tests check exhaustive coverage when the catalog changes.
export const romanianObjectGovernmentByFamily: Readonly<Record<string,
  'direct' | 'nested-direct' | 'preposition' | 'copular'>> = {
  'common-verb-061': 'preposition',
  'common-verb-062': 'preposition',
  'common-verb-063': 'preposition',
  'common-verb-064': 'preposition',
  'common-verb-065': 'preposition',
  'common-verb-066': 'preposition',
  'common-verb-067': 'preposition',
  'common-verb-068': 'preposition',
  'common-verb-069': 'preposition',
  'common-verb-070': 'preposition',
  'common-verb-071': 'preposition',
  'common-verb-001': 'direct',
  'common-verb-002': 'direct',
  'common-verb-003': 'direct',
  'common-verb-004': 'direct',
  'common-verb-005': 'direct',
  'common-verb-006': 'direct',
  'common-verb-007': 'direct',
  'common-verb-008': 'direct',
  'common-verb-009': 'direct',
  'common-verb-010': 'direct',
  'common-verb-011': 'direct',
  'common-verb-012': 'direct',
  'common-verb-013': 'direct',
  'common-verb-014': 'direct',
  'common-verb-015': 'direct',
  'common-verb-016': 'direct',
  'common-verb-017': 'direct',
  'common-verb-018': 'direct',
  'common-verb-019': 'direct',
  'common-verb-020': 'direct',
  'common-verb-021': 'direct',
  'common-verb-022': 'direct',
  'common-verb-023': 'copular',
  'common-verb-024': 'direct',
  'common-verb-025': 'direct',
  'common-verb-026': 'copular',
  'common-verb-027': 'copular',
  'common-verb-028': 'nested-direct',
  'common-verb-029': 'preposition',
  'common-verb-030': 'direct',
  'common-verb-031': 'direct',
  'common-verb-032': 'direct',
  'common-verb-033': 'direct',
  'common-verb-034': 'direct',
  'common-verb-035': 'direct',
  'common-verb-036': 'direct',
  'common-verb-037': 'direct',
  'common-verb-038': 'direct',
  'common-verb-039': 'direct',
  'common-verb-040': 'direct',
  'common-verb-041': 'direct',
  'common-verb-042': 'direct',
  'common-verb-043': 'direct',
  'common-verb-044': 'direct',
  'common-verb-045': 'direct',
  'common-verb-046': 'direct',
  'common-verb-047': 'direct',
  'common-verb-048': 'direct',
  'common-verb-049': 'direct',
  'common-verb-050': 'direct',
  'common-verb-051': 'direct',
  'common-verb-052': 'direct',
  'common-verb-053': 'preposition',
  'common-verb-054': 'preposition',
  'common-verb-055': 'preposition',
  'common-verb-056': 'preposition',
  'common-verb-057': 'preposition',
  'common-verb-058': 'preposition',
  'common-verb-059': 'preposition',
  'common-verb-060': 'preposition',
  'red-folded-chairman-verb-001': 'direct',
  'red-folded-chairman-verb-002': 'preposition',
  'red-folded-chairman-verb-003': 'preposition',
  'thunder-tribune-verb-001': 'nested-direct',
  'thunder-tribune-verb-002': 'nested-direct',
  'thunder-tribune-verb-003': 'preposition',
  'midnight-sensationalist-verb-001': 'nested-direct',
  'midnight-sensationalist-verb-002': 'preposition',
  'midnight-sensationalist-verb-003': 'preposition',
  'velvet-mogul-verb-001': 'nested-direct',
  'velvet-mogul-verb-002': 'preposition',
  'velvet-mogul-verb-003': 'preposition',
  'black-sea-captain-verb-001': 'direct',
  'black-sea-captain-verb-002': 'direct',
  'black-sea-captain-verb-003': 'preposition',
  'retiring-cassandra-verb-001': 'nested-direct',
  'retiring-cassandra-verb-002': 'nested-direct',
  'retiring-cassandra-verb-003': 'preposition',
  'oat-milk-reformist-verb-001': 'preposition',
  'oat-milk-reformist-verb-002': 'nested-direct',
  'oat-milk-reformist-verb-003': 'preposition',
  'marble-diplomat-verb-001': 'nested-direct',
  'marble-diplomat-verb-002': 'nested-direct',
  'marble-diplomat-verb-003': 'preposition',
  'county-baron-verb-001': 'direct',
  'county-baron-verb-002': 'direct',
  'county-baron-verb-003': 'preposition',
  'coalition-acrobat-verb-001': 'direct',
  'coalition-acrobat-verb-002': 'direct',
  'coalition-acrobat-verb-003': 'preposition',
  'algorithmic-prophet-verb-001': 'direct',
  'algorithmic-prophet-verb-002': 'preposition',
  'algorithmic-prophet-verb-003': 'preposition',
  'spreadsheet-technocrat-verb-001': 'preposition',
  'spreadsheet-technocrat-verb-002': 'preposition',
  'spreadsheet-technocrat-verb-003': 'preposition',
  'football-tycoon-verb-001': 'preposition',
  'football-tycoon-verb-002': 'preposition',
  'football-tycoon-verb-003': 'preposition',
  'luxury-minister-verb-001': 'direct',
  'luxury-minister-verb-002': 'direct',
  'luxury-minister-verb-003': 'preposition',
  'diaspora-oracle-verb-001': 'direct',
  'diaspora-oracle-verb-002': 'direct',
  'diaspora-oracle-verb-003': 'preposition',
  'apartment-block-geopolitician-verb-001': 'direct',
  'apartment-block-geopolitician-verb-002': 'direct',
  'apartment-block-geopolitician-verb-003': 'preposition',
  'eu-funds-alchemist-verb-001': 'direct',
  'eu-funds-alchemist-verb-002': 'preposition',
  'eu-funds-alchemist-verb-003': 'preposition',
  'government-ai-verb-001': 'direct',
  'government-ai-verb-002': 'preposition',
  'government-ai-verb-003': 'direct',
  'reluctant-theorem-verb-001': 'preposition',
  'reluctant-theorem-verb-002': 'preposition',
  'reluctant-theorem-verb-003': 'preposition',
};

// A nested direct object follows the final verb after this clause anchor.
export const romanianNestedObjectAnchorByFamily: Readonly<Record<string,
  'să ' | 'de a ' | 'care ' | 'și '>> = {
  'common-verb-028': 'să ',
  'thunder-tribune-verb-001': 'și ',
  'thunder-tribune-verb-002': 'să ',
  'midnight-sensationalist-verb-001': 'să ',
  'velvet-mogul-verb-001': 'de a ',
  'retiring-cassandra-verb-001': 'care ',
  'retiring-cassandra-verb-002': 'să ',
  'oat-milk-reformist-verb-002': 'să ',
  'marble-diplomat-verb-001': 'să ',
  'marble-diplomat-verb-002': 'să ',
};

export const romanianPersonalObjectByNounId: Readonly<Record<string, Readonly<{
  directText: string;
  clitic: 'polite-second' | 'masculine-singular' | 'masculine-plural' | 'feminine-singular' | null;
}>>> = {
  'common-noun-028': { directText: "pe dumneavoastră", clitic: 'polite-second' },
  'common-noun-031': { directText: "pe votanții voștri", clitic: 'masculine-plural' },
  'common-noun-032': { directText: "o scroafă", clitic: null },
  'common-noun-033': { directText: "un hoț", clitic: null },
  'common-noun-036': { directText: "pe fratele vostru", clitic: 'masculine-singular' },
  'common-noun-037': { directText: "pe tatăl vostru", clitic: 'masculine-singular' },
  'common-noun-038': { directText: "pe vărul vostru", clitic: 'masculine-singular' },
  'common-noun-039': { directText: "pe ginerele vostru", clitic: 'masculine-singular' },
  'common-noun-040': { directText: "pe partenerul vostru cu post public rezervat", clitic: 'masculine-singular' },
  'common-noun-042': { directText: "un nomenclaturist de cartier", clitic: null },
  'common-noun-043': { directText: "un comunist", clitic: null },
  'common-noun-044': { directText: "un străin", clitic: null },
  'common-noun-045': { directText: "un globalist", clitic: null },
  'common-noun-046': { directText: "un suveranist", clitic: null },
  'common-noun-047': { directText: "un fascist", clitic: null },
  'common-noun-048': { directText: "un porc", clitic: null },
  'common-noun-049': { directText: "un nazist", clitic: null },
  'common-noun-051': { directText: "un secretar de stat", clitic: null },
  'common-noun-052': { directText: "o vrăjitoare", clitic: null },
  'red-folded-chairman-noun-002': { directText: "o fosilă din sala de comisii, nu din popor", clitic: null },
  'red-folded-chairman-noun-005': { directText: "un gânditor liber pe statul de plată al poporului", clitic: null },
  'red-folded-chairman-noun-007': { directText: "pe oamenii muncii", clitic: 'masculine-plural' },
  'thunder-tribune-noun-001': { directText: "pe acea sperietoare de la ora de maximă audiență", clitic: 'feminine-singular' },
  'thunder-tribune-noun-002': { directText: "pe acea sperietoare pudrată din balconul oficial", clitic: 'feminine-singular' },
  'thunder-tribune-noun-004': { directText: "o trâmbiță de partid care chițăie", clitic: null },
  'thunder-tribune-noun-005': { directText: "un funcționar de comisie posedat de un difuzor", clitic: null },
  'thunder-tribune-noun-006': { directText: "o șomâldoacă", clitic: null },
  'black-sea-captain-noun-003': { directText: "un păun de port cu privilegii de amiral, mereu voios", clitic: null },
  'black-sea-captain-noun-005': { directText: "un căpitan fără busolă, dar cu soare în suflet", clitic: null },
  'spreadsheet-technocrat-noun-003': { directText: "un cetățean mediu trecut la rubrica altele", clitic: null },
  'football-tycoon-noun-006': { directText: "o coloană a vinovăției fără patron", clitic: null },
};

// A preposition may govern a case other than the unmarked noun form. These
// families need an authored object construction before arbitrary noun pairing.
export const romanianSpecialObjectCaseByFamily: Readonly<Record<string,
  'genitive' | 'contract-indefinite' | 'predicate-complement'>> = {
  'red-folded-chairman-verb-003': 'contract-indefinite',
  'velvet-mogul-verb-002': 'contract-indefinite',
  'common-verb-053': 'contract-indefinite',
  'common-verb-071': 'contract-indefinite',
  'algorithmic-prophet-verb-003': 'contract-indefinite',
  'common-verb-055': 'predicate-complement',
  'diaspora-oracle-verb-003': 'predicate-complement',
};
