// Romanian object government is authored per semantic tense family. Every
// verb family and every personal noun in the shipped catalog has an entry.
// The grammar tests check exhaustive coverage when the catalog changes.
export const romanianObjectGovernmentByFamily: Readonly<Record<string,
  'direct' | 'nested-direct' | 'preposition' | 'copular'>> = {
  'general-postpones-the-reform': 'preposition',
  'general-rehearses-the-emergency': 'preposition',
  'transition-era-television-studio-archives-the-revolution': 'preposition',
  'modern-debate-studio-rehearses-the-closing-statement': 'preposition',
  'county-council-ballroom-counts-the-ribbon-twice': 'preposition',
  'midnight-call-in-studio-advertises-the-hidden-tape': 'preposition',
  'palace-press-hall-guards-the-empty-envelope': 'preposition',
  'influencer-campaign-livestream-sponsors-the-ancient-truth': 'preposition',
  'civic-cypher-boxing-ring-dropped-the-needle-beside': 'preposition',
  'civic-cypher-boxing-ring-answered-the-bell-with': 'preposition',
  'civic-cypher-boxing-ring-mixed-the-crowd-noise-into': 'preposition',
  'denounced': 'direct',
  'postpones': 'direct',
  'inaugurates': 'direct',
  'privatizes': 'direct',
  'broadcasts': 'direct',
  'explains': 'direct',
  'announces': 'direct',
  'archives': 'direct',
  'negotiated': 'direct',
  'rebrands': 'direct',
  'consulted': 'direct',
  'allocated': 'direct',
  'contested': 'direct',
  'promised': 'direct',
  'unveiled': 'direct',
  'coordinated': 'direct',
  'audits': 'direct',
  'redirects': 'direct',
  'televises': 'direct',
  'embarrasses': 'direct',
  'disowns': 'direct',
  'heckles': 'direct',
  'be': 'copular',
  'stole': 'direct',
  'appropriated': 'direct',
  'not-be': 'copular',
  'will-never-be': 'copular',
  'public-outsourced-explanation': 'nested-direct',
  'public-missing-report': 'preposition',
  'public-commemorative-plaque': 'direct',
  'public-velvet-rope': 'direct',
  'public-public-invoice': 'direct',
  'public-visitor-badge': 'direct',
  'public-tracking-number': 'direct',
  'public-seating-plan': 'direct',
  'public-consultation-fee': 'direct',
  'public-procurement-emergency': 'direct',
  'public-forwarded-complaint': 'direct',
  'public-lost-receipt': 'direct',
  'public-ribbon-ceremony': 'direct',
  'transition-era-television-studio-relation-1': 'direct',
  'transition-era-television-studio-relation-2': 'direct',
  'modern-debate-studio-relation-1': 'direct',
  'modern-debate-studio-relation-2': 'direct',
  'county-council-ballroom-relation-1': 'direct',
  'county-council-ballroom-relation-2': 'direct',
  'midnight-call-in-studio-relation-1': 'direct',
  'midnight-call-in-studio-relation-2': 'direct',
  'palace-press-hall-relation-1': 'direct',
  'palace-press-hall-relation-2': 'direct',
  'influencer-campaign-livestream-relation-1': 'direct',
  'influencer-campaign-livestream-relation-2': 'direct',
  'general-audits-the-ceremony': 'preposition',
  'general-sponsors-the-apology': 'preposition',
  'general-relabels-the-pothole': 'preposition',
  'general-files-the-ribbon': 'preposition',
  'general-measures-the-silence': 'preposition',
  'general-exports-the-excuse': 'preposition',
  'general-approves-the-invoice': 'preposition',
  'general-broadcasts-the-rumour': 'preposition',
  'mediates': 'direct',
  'red-folded-chairman-verb-1': 'preposition',
  'red-folded-chairman-contract-verb-files-the-transition': 'preposition',
  'condemns': 'nested-direct',
  'thunder-tribune-verb-1': 'nested-direct',
  'thunder-tribune-contract-verb-announces-the-evidence-loudly': 'preposition',
  'midnight-sensationalist-verb-1': 'nested-direct',
  'midnight-sensationalist-verb-2': 'preposition',
  'midnight-sensationalist-contract-verb-turns-rumour-into-ratings': 'preposition',
  'velvet-mogul-verb-1': 'nested-direct',
  'velvet-mogul-verb-2': 'preposition',
  'velvet-mogul-contract-verb-buys-influence-before-breakfast': 'preposition',
  'steers': 'direct',
  'captain-grounds': 'direct',
  'black-sea-captain-contract-verb-sails-past-official-explanation': 'preposition',
  'retiring-cassandra-verb-1': 'nested-direct',
  'retiring-cassandra-verb-2': 'nested-direct',
  'retiring-cassandra-contract-verb-delivers-the-result-late': 'preposition',
  'oat-milk-reformist-verb-1': 'preposition',
  'oat-milk-reformist-verb-2': 'nested-direct',
  'oat-milk-reformist-contract-verb-serves-relevance-with-foam': 'preposition',
  'marble-diplomat-verb-1': 'nested-direct',
  'marble-diplomat-verb-2': 'nested-direct',
  'marble-diplomat-contract-verb-serves-luxury-as-protocol': 'preposition',
  'county-baron-verb-1': 'direct',
  'county-baron-verb-2': 'direct',
  'county-baron-contract-verb-counts-ribbon-twice': 'preposition',
  'coalition-acrobat-rented-to-both-sides': 'direct',
  'coalition-acrobat-traded-for-cabinet-seats': 'direct',
  'coalition-acrobat-contract-verb-rehearses-opposite-coalition': 'preposition',
  'algorithmic-prophet-decoded-from-static': 'direct',
  'algorithmic-prophet-certified-by-pendulum': 'preposition',
  'algorithmic-prophet-contract-verb-predicts-drought-from-coffee-ring': 'preposition',
  'spreadsheet-technocrat-rounded-out-of-budget': 'preposition',
  'spreadsheet-technocrat-buried-in-appendix': 'preposition',
  'spreadsheet-technocrat-contract-verb-measures-delivery-by-dashboard': 'preposition',
  'football-tycoon-sold-naming-rights-to': 'preposition',
  'football-tycoon-relegated-to-fine-print': 'preposition',
  'football-tycoon-contract-verb-sells-sincerity-at-halftime': 'preposition',
  'luxury-minister-upgraded-to-silk': 'direct',
  'luxury-minister-charged-to-hardship-fund': 'direct',
  'luxury-minister-contract-verb-measures-service-in-marble': 'preposition',
  'diaspora-oracle-diagnosed-by-postcard': 'direct',
  'diaspora-oracle-corrected-from-departure-gate': 'direct',
  'diaspora-oracle-contract-verb-translates-distance-into-evidence': 'preposition',
  'apartment-block-geopolitician-mapped-with-fridge-magnets': 'direct',
  'apartment-block-geopolitician-verified-through-wall': 'direct',
  'apartment-block-geopolitician-contract-verb-maps-crisis-from-third-floor': 'preposition',
  'eu-funds-alchemist-converted-into-launch-costs': 'direct',
  'eu-funds-alchemist-hid-behind-funding-plaque': 'preposition',
  'eu-funds-alchemist-contract-verb-converts-grant-into-ribbon': 'preposition',
  'government-ai-procures': 'direct',
  'government-ai-double-clicks-on': 'preposition',
  'optimizes': 'direct',
  'reluctant-theorem-postponed-decision': 'preposition',
  'reluctant-theorem-missed-deadline': 'preposition',
  'reluctant-theorem-contract-verb-postpones-the-proof': 'preposition',
};

// A nested direct object follows the final verb after this clause anchor.
export const romanianNestedObjectAnchorByFamily: Readonly<Record<string,
  'să ' | 'de a ' | 'care ' | 'și '>> = {
  'public-outsourced-explanation': 'să ',
  'condemns': 'și ',
  'thunder-tribune-verb-1': 'să ',
  'midnight-sensationalist-verb-1': 'să ',
  'velvet-mogul-verb-1': 'de a ',
  'retiring-cassandra-verb-1': 'care ',
  'retiring-cassandra-verb-2': 'să ',
  'oat-milk-reformist-verb-2': 'să ',
  'marble-diplomat-verb-1': 'să ',
  'marble-diplomat-verb-2': 'să ',
};

export const romanianPersonalObjectByNounId: Readonly<Record<string, Readonly<{
  directText: string;
  clitic: 'polite-second' | 'masculine-singular' | 'masculine-plural' | 'feminine-singular' | null;
}>>> = {
  'you': { directText: "pe dumneavoastră", clitic: 'polite-second' },
  'your-voters': { directText: "pe votanții voștri", clitic: 'masculine-plural' },
  'a-sow': { directText: "o scroafă", clitic: null },
  'a-thief': { directText: "un hoț", clitic: null },
  'your-brother': { directText: "pe fratele vostru", clitic: 'masculine-singular' },
  'your-father': { directText: "pe tatăl vostru", clitic: 'masculine-singular' },
  'your-cousin': { directText: "pe vărul vostru", clitic: 'masculine-singular' },
  'your-son-in-law': { directText: "pe ginerele vostru", clitic: 'masculine-singular' },
  'your-concubine': { directText: "pe partenerul vostru cu post public rezervat", clitic: 'masculine-singular' },
  'a-neighborhood-apparatchik': { directText: "un nomenclaturist de cartier", clitic: null },
  'a-communist': { directText: "un comunist", clitic: null },
  'a-liberal': { directText: "un liberal", clitic: null },
  'a-globalist': { directText: "un globalist", clitic: null },
  'a-sovereignist': { directText: "un suveranist", clitic: null },
  'a-fascist': { directText: "un fascist", clitic: null },
  'a-pig': { directText: "un porc", clitic: null },
  'a-nazi': { directText: "un nazist", clitic: null },
  'a-state-secretary': { directText: "un secretar de stat", clitic: null },
  'a-witch': { directText: "o vrăjitoare", clitic: null },
  'my-opponent': { directText: "pe adversarul meu", clitic: 'masculine-singular' },
  'a-committee-room-fossil': { directText: "o fosilă din sala de comisii, nu din popor", clitic: null },
  'a-free-thinker': { directText: "un gânditor liber pe statul de plată al poporului", clitic: null },
  'the-working-class': { directText: "pe oamenii muncii", clitic: 'masculine-plural' },
  'tribunes-indictment': { directText: "pe acea sperietoare de la ora de maximă audiență", clitic: 'feminine-singular' },
  'that-powdered-scarecrow': { directText: "pe acea sperietoare pudrată din balconul oficial", clitic: 'feminine-singular' },
  'a-squealing-party-trumpet': { directText: "o trâmbiță de partid care chițăie", clitic: null },
  'a-cursed-gnome': { directText: "un funcționar de comisie posedat de un difuzor", clitic: null },
  'a-somaldoaca': { directText: "o șomâldoacă", clitic: null },
  'a-dockside-peacock': { directText: "un păun de port cu privilegii de amiral, mereu voios", clitic: null },
  'a-captain-without-compass': { directText: "un căpitan fără busolă, dar cu soare în suflet", clitic: null },
  'spreadsheet-technocrat-average-citizen': { directText: "un cetățean mediu trecut la rubrica altele", clitic: null },
  'football-tycoon-blameless-owner': { directText: "o coloană a vinovăției fără patron", clitic: null },
};

// A preposition may govern a case other than the unmarked noun form. These
// families need an authored object construction before arbitrary noun pairing.
export const romanianSpecialObjectCaseByFamily: Readonly<Record<string,
  'genitive' | 'contract-indefinite' | 'predicate-complement'>> = {
  'red-folded-chairman-contract-verb-files-the-transition': 'contract-indefinite',
  'velvet-mogul-verb-2': 'contract-indefinite',
  'general-audits-the-ceremony': 'contract-indefinite',
  'civic-cypher-boxing-ring-mixed-the-crowd-noise-into': 'contract-indefinite',
  'algorithmic-prophet-contract-verb-predicts-drought-from-coffee-ring': 'contract-indefinite',
  'general-relabels-the-pothole': 'predicate-complement',
  'diaspora-oracle-contract-verb-translates-distance-into-evidence': 'predicate-complement',
};
