import { validateContentCatalog } from './content-catalog';
import { englishGameLocale } from '../localization/en-game-locale';

const approvedReview = {
  state: 'approved' as const,
  originality: 'original' as const,
  safetyFlags: [],
  notes: 'Original fictional wordplay. Editorial safety checklist complete.',
};

const media = (assetId: string) => ({
  assetId,
  realLogo: false,
  copyrightedBroadcastGraphic: false,
});

export const sampleContent = validateContentCatalog({
  phrases: [
    {
      id: 'paper-promise',
      role: 'noun',
      textKey: 'phrase.paper-promise',
      numberForms: {
        singularKey: 'phrase.paper-promise.singular',
        pluralKey: 'phrase.paper-promise.plural',
      },
      baseValue: 2,
      directness: 0,
      tags: ['empty-promise', 'paperwork'],
      rarity: 'common',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'velvet-megaphone',
      role: 'noun',
      textKey: 'phrase.velvet-megaphone',
      baseValue: 3,
      directness: 0,
      tags: ['grandstanding', 'noise'],
      rarity: 'uncommon',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'folds',
      role: 'verb',
      textKey: 'phrase.folds',
      numberForms: {
        singularKey: 'phrase.folds.singular',
        pluralKey: 'phrase.folds.plural',
      },
      baseValue: 2,
      directness: 1,
      tags: ['empty-promise', 'retreat'],
      rarity: 'common',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'outshouts',
      role: 'verb',
      textKey: 'phrase.outshouts',
      numberForms: {
        singularKey: 'phrase.outshouts.singular',
        pluralKey: 'phrase.outshouts.plural',
      },
      baseValue: 3,
      directness: 1,
      tags: ['grandstanding', 'noise'],
      rarity: 'common',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'before-lunch',
      role: 'predicate',
      textKey: 'phrase.before-lunch',
      baseValue: 2,
      directness: 0,
      tags: ['empty-promise', 'retreat'],
      rarity: 'common',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'in-an-empty-hall',
      role: 'predicate',
      textKey: 'phrase.in-an-empty-hall',
      baseValue: 3,
      directness: 0,
      tags: ['grandstanding', 'noise'],
      rarity: 'uncommon',
      finisherBonus: 2,
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'committee-kite',
      role: 'noun',
      textKey: 'phrase.committee-kite',
      baseValue: 3,
      directness: 0,
      tags: ['paperwork', 'empty-promise'],
      characterIds: ['civic-fox'],
      sceneIds: ['echo-chamber'],
      rarity: 'rare',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'polishes',
      role: 'verb',
      textKey: 'phrase.polishes',
      numberForms: {
        singularKey: 'phrase.polishes.singular',
        pluralKey: 'phrase.polishes.plural',
      },
      baseValue: 2,
      directness: 0,
      tags: ['grandstanding', 'paperwork'],
      characterIds: ['brass-peacock'],
      rarity: 'uncommon',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'past-the-deadline',
      role: 'predicate',
      textKey: 'phrase.past-the-deadline',
      baseValue: 4,
      directness: 1,
      tags: ['retreat', 'noise'],
      sceneIds: ['echo-chamber'],
      rarity: 'rare',
      finisherBonus: 3,
      contentRating: 'teen',
      editorialReview: approvedReview,
    },
    {
      id: 'and',
      role: 'conjunction',
      textKey: 'phrase.and',
      baseValue: 2,
      directness: 0,
      tags: ['paperwork', 'noise'],
      rarity: 'uncommon',
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'with-the-receipt',
      role: 'ending',
      textKey: 'phrase.with-the-receipt',
      baseValue: 3,
      directness: 1,
      tags: ['empty-promise', 'paperwork'],
      rarity: 'uncommon',
      finisherBonus: 2,
      contentRating: 'everyone-10-plus',
      editorialReview: approvedReview,
    },
    {
      id: 'still-echoes',
      role: 'continuation',
      textKey: 'phrase.still-echoes',
      baseValue: 3,
      directness: 1,
      tags: ['grandstanding', 'retreat'],
      rarity: 'rare',
      contentRating: 'teen',
      editorialReview: approvedReview,
    },
  ],
  characters: [
    {
      id: 'civic-fox',
      nameKey: 'character.civic-fox.name',
      descriptionKey: 'character.civic-fox.description',
      assets: {
        portrait: media('civic-fox-portrait'),
        token: media('civic-fox-token'),
      },
      palette: { primary: '#783f2a', secondary: '#f0c36d', accent: '#2f6b59' },
      weaknessTags: ['grandstanding', 'noise'],
      phrasePools: {
        public: ['paper-promise', 'velvet-megaphone', 'folds', 'and'],
        private: ['outshouts', 'before-lunch', 'committee-kite'],
      },
      comebackLinesByTier: {
        weak: ['comeback.civic-fox.weak'],
        medium: ['comeback.civic-fox.medium'],
        strong: ['comeback.civic-fox.strong'],
      },
      aiPersonality: { aggression: 0.45, denial: 0.8, risk: 0.35 },
      voiceProfile: { voiceHint: 'measured', rate: 0.95, pitch: 0.9 },
      animationSet: {
        idle: 'civic-fox-idle',
        speak: 'civic-fox-speak',
        react: 'civic-fox-react',
      },
    },
    {
      id: 'brass-peacock',
      nameKey: 'character.brass-peacock.name',
      descriptionKey: 'character.brass-peacock.description',
      assets: {
        portrait: media('brass-peacock-portrait'),
        token: media('brass-peacock-token'),
      },
      palette: { primary: '#244b66', secondary: '#d28c2c', accent: '#b33f62' },
      weaknessTags: ['empty-promise', 'retreat', 'paperwork'],
      phrasePools: {
        public: [
          'paper-promise',
          'folds',
          'before-lunch',
          'with-the-receipt',
          'still-echoes',
        ],
        private: ['velvet-megaphone', 'polishes', 'past-the-deadline'],
      },
      comebackLinesByTier: {
        weak: ['comeback.brass-peacock.weak'],
        medium: ['comeback.brass-peacock.medium'],
        strong: ['comeback.brass-peacock.strong'],
      },
      aiPersonality: { aggression: 0.75, denial: 0.35, risk: 0.65 },
      voiceProfile: { voiceHint: 'bright', rate: 1.05, pitch: 1.1 },
      animationSet: {
        idle: 'brass-peacock-idle',
        speak: 'brass-peacock-speak',
        react: 'brass-peacock-react',
      },
    },
  ],
  scenes: [
    {
      id: 'echo-chamber',
      nameKey: 'scene.echo-chamber.name',
      descriptionKey: 'scene.echo-chamber.description',
      backgroundLayers: [
        { media: media('echo-chamber-backdrop'), depth: 0 },
        { media: media('echo-chamber-balcony'), depth: 0.65 },
      ],
      animationId: 'echo-chamber-dust',
      music: media('echo-chamber-theme'),
      ambience: media('echo-chamber-room-tone'),
      phrasePool: [
        'paper-promise',
        'velvet-megaphone',
        'folds',
        'outshouts',
        'before-lunch',
        'in-an-empty-hall',
        'committee-kite',
        'past-the-deadline',
        'and',
        'with-the-receipt',
        'still-echoes',
      ],
      effectIds: ['paper-flutter', 'balcony-flicker'],
    },
  ],
  locales: [englishGameLocale],
});
